### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by edavur** [causalens/dara#106]
I have two different problems: 

1. Ouput from terminal on Windows 10 with the git bash shell:
C:\Users\DARA> create-dara-app 
create-dara-app : Die Benennung "create-dara-app" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die 
Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ create-dara-app
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (create-dara-app:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

2. Ouput from terminal on Windows 10 with the git bash shell:
- I am using python 3.10.9 on Windows 10.
Other installed tools: 
- Successfully installed setuptools-68.2.2

Successfully installed MarkupSafe-2.1.3 PyYAML-6.0.1 aiofiles-23.2.1 anyio-4.0.0 arrow-1.3.0 async-asgi-testclient-1.4.11 binaryornot-0.4.4 black-22.1.0 blue-0.9.1 bokeh-3.1.1 cai-causal-graph-0.2.6 certifi-2023.7.22 cffi-1.16.0 chardet-5.2.0 charset-normalizer-3.3.0 click-8.1.3 colorama-0.4.6 contourpy-1.1.1 cookiecutter-2.4.0 create-dara-app-1.3.0 croniter-1.4.1 cryptography-41.0.4 cycler-0.12.1 dara-components-1.3.0 dara-core-1.3.0 defusedxml-0.7.1 dill-0.3.7 et-xmlfile-1.1.0 exceptiongroup-1.1.3 fastapi-0.95.2 fastapi-vite-0.3.1 flake8-4.0.1 fonttools-4.43.1 h11-0.14.0 httpcore-0.18.0 httptools-0.6.0 httpx-0.25.0 idna-3.4 isort-5.12.0 jinja2-3.0.3 kiwisolver-1.4.5 markdown-it-py-3.0.0 matplotlib-3.8.0 mccabe-0.6.1 mdurl-0.1.2 multidict-6.0.4 mypy-extensions-1.0.0 networkx-3.1 numpy-1.26.0 odfpy-1.4.1 openpyxl-3.1.2 packaging-23.2 pandas-2.1.1 pathspec-0.11.2 pillow-10.0.1 platformdirs-3.11.0 plotly-5.14.1 prometheus-client-0.14.1 pyarrow-13.0.0 pycodestyle-2.8.0 pycparser-2.21 pydantic-1.10.13 pyflakes-2.4.0 pygments-2.16.1 pyjwt-2.8.0 pyparsing-3.1.1 python-dateutil-2.8.2 python-dotenv-0.19.2 python-multipart-0.0.5 python-slugify-8.0.1 pytz-2023.3.post1 pyxlsb-1.0.10 requests-2.31.0 responses-0.18.0 rich-13.6.0 scipy-1.11.3 seaborn-0.13.0 six-1.16.0 sniffio-1.3.0 starlette-0.27.0 tblib-1.7.0 tenacity-8.2.3 test-0.1.0 text-unidecode-1.3 toml-0.10.2 tomli-2.0.1 tornado-6.3.3 types-python-dateutil-2.8.19.14 typing-extensions-4.5.0 tzdata-2023.3 urllib3-2.0.6 uvicorn-0.22.0 watchfiles-0.20.0 websockets-11.0.3 xlrd-2.0.1 xyzservices-2023.10.0

MINGW64 /c/Code /dara $ create-dara-app
WARNING:create-dara-app:Poetry not found. Falling back to pip.
  [1/2] project_name (Decision App): test
  [2/2] author_name (Author <[author@example.com](mailto:author@example.com)>): test
Lots of ouput …, but successful.

username@computer MINGW64 /c/Code/dara/test$ source .venv/Scripts/activate
(.venv)
username@computer MINGW64 /c/Code/dara/test$ dara start
2023-10-10 15:53:25,993  WARNING  uvicorn.error  Current configuration will not reload as not all conditions are met, please refer to documentation.
Traceback (most recent call last):
  File "C:\Tools\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Tools\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Code\dara\test\.venv\Scripts\dara.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Code\dara\test\.venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Code\\dara\test\.venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Code\dara\test\.venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Code\\dara\test\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Code\\dara\test\.venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Code\\dara\test\.venv\lib\site-packages\dara\core\cli.py", line 140, in start
    uvicorn.run(
  File "C:\Code\dara\test\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Code\dara\test\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Tools\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Tools\Python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Code\dara\test\.venv\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Code\dara\test\.venv\lib\site-packages\uvicorn\config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Code\dara\test\.venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Code\dara\test\.venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Tools\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Code\dara\test\.venv\lib\site-packages\dara\core\main.py", line 44, in <module>
    from dara.core.internal.cgroup import get_cpu_count, set_memory_limit
  File "C:\Code\dara\test\.venv\lib\site-packages\dara\core\internal\cgroup.py", line 21, in <module>
    import resource
ModuleNotFoundError: No module named 'resource

**Comment by krzysztof-causalens** [comment]
Hello,

Thanks for reporting the issue. The issue stems from our usage of the `resource` package for limiting memory usage within containers (which is set with env `CGROUP_MEMORY_LIMIT_ENABLED`). It looks like the package is unix-specific and is not available for Windows machines - we have not tested Dara on Windows before so I appreciate there might be bumps in the road we hit along the line. 

We will make a patch to guard that functionality for non-windows OS-es, a workaround would be to use something like WSL. I'll let you know when this is resolved.

**Comment by krzysztof-causalens** [comment]
Fix has been released in 1.3.1
