### ISSUE TITLE
ImportError: We could not import your configuration from here: my_first_app.main:config

### ISSUE THREAD

**Issue by gsal** [causalens/dara#334]
Hi, run into Dara a couple of days ago...

I just started to read the docs and to follow the [Quick Start](https://dara.causalens.com/docs/generated/dara/docs/quickstart/) guide....run into trouble right away.  After removing the initial `Heading` and adding the new `eda_page()`, I get the following error:

```
ImportError: We could not import your configuration from here: my_first_app.main:config. There might be an error in the stacktrace above. 
Otherwise it likely means you are using a non-standard location and need to pass the --config location directly. 
If Dara is still failing to resolve your module, make sure your package is installed and accessible in the current virtual environment; 
 as a last resort, try reactivating/recreating the venv.
```

What to do?

**Comment by krzysztof-causalens** [comment]
Hi, 
as per the generic error, this occurs whenever any error is raised as Dara tries to import your main module. In the majority of the cases, if the project is set up correctly, the root cause of the problem is elsewhere in the stacktrace. 
Unfortunately, we can't really say what's wrong just from this snippet - we'll need more detail. Could you post the entire stacktrace, or simply all of the Dara logs from when you run `dara start`?

**Comment by gsal** [comment]
```
tree
.
├── my_first_app
│   ├── definitions.py
│   ├── __init__.py
│   ├── main.py
│   ├── pages
│   │   └── eda.py
│   └── __pycache__
│       ├── __init__.cpython-311.pyc
│       └── main.cpython-311.pyc
├── poetry.lock
├── pyproject.toml
└── README.md

```

```
poetry run dara start
 2024-07-05 12:25:14,763  INFO  dara.dev  Loading configuration from my_first_app.main:config 
Traceback (most recent call last):
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/dara/core/internal/utils.py", line 127, in import_config
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usw/spgtools/python3/3.11.2/rocky9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/salazag/programming/python/dara/my_first_app/my_first_app/main.py", line 9, in <module>
    config.add_page('EDA', eda_page())
                           ^^^^^^^^
NameError: name 'eda_page' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/salazag/programming/python/dara/my_first_app/.venv/bin/dara", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/dara/core/cli.py", line 170, in start
    uvicorn.run(
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usw/spgtools/python3/3.11.2/rocky9/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usw/spgtools/python3/3.11.2/rocky9/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = self.loaded_app()
                      ^^^^^^^^^^^^^^^^^
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/dara/core/main.py", line 426, in start
    config_module, config = import_config(config_path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salazag/programming/python/dara/my_first_app/.venv/lib/python3.11/site-packages/dara/core/internal/utils.py", line 130, in import_config
    raise ImportError(
ImportError: We could not import your configuration from here: my_first_app.main:config. There might be an error in the stacktrace above. 
Otherwise it likely means you are using a non-standard location and need to pass the --config location directly. 
If Dara is still failing to resolve your module, make sure your package is installed and accessible in the current virtual environment; 
 as a last resort, try reactivating/recreating the venv.
```

**Comment by krzysztof-causalens** [comment]
Thanks for providing the stacktrace. The error is quite clear: 

```
  File "/home/salazag/programming/python/dara/my_first_app/my_first_app/main.py", line 9, in <module>
    config.add_page('EDA', eda_page())
                           ^^^^^^^^
NameError: name 'eda_page' is not defined
```

Looks like you haven't imported the `eda_page` into the main file

**Comment by gsal** [comment]
Doh! Silly me. Sorry about that....I recall understanding to replace the add_page entry in main, but overlooked the part about having to import. 
Thanks for the prompt replies.
